import React from "react";
import "../styles/wordList.css";

function WordList() {
  return (
    <div className="word-list-container">
      <h2>Seznam slov</h2>
      <p>Toto je seznam slov, které aplikace dokáže rozeznat.</p>
      <table className="word-list-table">
        <thead>
          <tr>
            <th>Současné tvary</th>
            <th>Staré tvary</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <ul>
                <li>cit</li>
                <li>cíditi</li>
                <li>cítiti</li>
                <li>cizí</li>
                <li>čelist</li>
                <li>číti</li>
                <li>jih</li>
                <li>Jiří</li>
                <li>jitro</li>
                <li>klíče</li>
                <li>kožich</li>
                <li>líbati</li>
                <li>plíce</li>
                <li>seno</li>
                <li>duše</li>
                <li>duše</li>
                <li>říjen</li>
                <li>šťír</li>
                <li>ťisíc</li>
                <li>vúňe</li>
                <li>muže</li>
                <li>vjeno</li>
                <li>místo</li>
                <li>mňesto</li>
                <li>dílo</li>
                <li>míra</li>
                <li>čert</li>
                <li>červený</li>
                <li>žerď</li>
                <li>Br̥do</li>
                <li>vr̥ba</li>
                <li>sr̥dce</li>
                <li>vl̥k</li>
                <li>cesta</li>
                <li>řeka</li>
                <li>kúň</li>
                <li>búh</li>
                <li>dúm</li>
                <li>dúl</li>
                <li>dvúr</li>
                <li>soud</li>
                <li>soused</li>
                <li>budoucí</li>
                <li>míra</li>
                <li>víra</li>
                <li>luk</li>
                <li>vúči</li>
                <li>svúj</li>
                <li>vejce</li>
                <li>krejčí</li>
                <li>misleti</li>
                <li>sin</li>
                <li>jazik</li>
                <li>ješťe</li>
                <li>šťesťí</li>
                <li>zelí</li>
                <li>šťáva</li>
                <li>nebožťík</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>c'ut</li>
                <li>c'úditi</li>
                <li>c'utiti</li>
                <li>c'uzí</li>
                <li>čel'ust</li>
                <li>čúti</li>
                <li>juh</li>
                <li>Juří</li>
                <li>jutro</li>
                <li>kl'účě</li>
                <li>kožuch</li>
                <li>l'úbati</li>
                <li>pl'úcě</li>
                <li>sěno</li>
                <li>dušě</li>
                <li>dušě</li>
                <li>řújen</li>
                <li>ščúr</li>
                <li>tis'úc</li>
                <li>wóňe</li>
                <li>mužě</li>
                <li>věno</li>
                <li>mě̄sto</li>
                <li>město</li>
                <li>dě̄lo</li>
                <li>mě̄ra</li>
                <li>čr̥t</li>
                <li>čr̥wený</li>
                <li>žr̥ď</li>
                <li>Bir̥do</li>
                <li>vir̥ba</li>
                <li>sir̥dce</li>
                <li>wil̥k</li>
                <li>cěsta</li>
                <li>řěka</li>
                <li>kóň</li>
                <li>bóh</li>
                <li>dóm</li>
                <li>dól</li>
                <li>dwór</li>
                <li>súd</li>
                <li>súsěd</li>
                <li>budúcí</li>
                <li>mě̄ra</li>
                <li>wě̄ra</li>
                <li>łuk</li>
                <li>wóči</li>
                <li>swój</li>
                <li>wajce</li>
                <li>krajčí</li>
                <li>mysleti</li>
                <li>syn</li>
                <li>jazyk</li>
                <li>ješče</li>
                <li>ščestí</li>
                <li>zelé</li>
                <li>ščáva</li>
                <li>nebožčík</li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default WordList;
